import type { KnuLink } from "./types";

/**
 * 경북대학교 관련 사이트 목록 — 단일 진실 공급원.
 *
 * 수록 원칙
 *  1. 실제로 접속을 확인한 URL만 넣는다. 추측한 주소는 넣지 않는다.
 *  2. `id`는 통계 키다. 학교가 URL을 바꾸더라도 `id`는 바꾸지 않는다.
 *  3. `keywords`에는 사람들이 실제로 칠 법한 말을 넣는다.
 *     초성 검색은 `name`과 `keywords`에서 자동으로 파생되므로 따로 적지 않는다.
 *  4. `healthException`은 curl 실측으로 확인된 것만. 자세한 사정은 아래.
 *
 * 헬스체크 예외의 근거 (2026-07 실측)
 *  - sugang / knuin / oz      : 브라우저가 아닌 요청에 HTTP 500을 돌려준다.
 *                               DNS는 155.230.130.x 로 정상 해석되고 실제로는 살아있다.
 *  - certpia                  : CNAME이 knu.certpia.com 이라 인증서 이름이 어긋난다.
 *  - toegye / cmri            : 인증서가 만료됐다(이름 불일치가 아니라 기간 만료).
 *                               브라우저가 경고를 띄우지만 사이트 자체는 살아있다.
 *
 * http:// 로 등록된 것들 (sei, riss, msrc, nrs, a3di)
 *  https 포트 자체가 응답하지 않는다(핸드셰이크 타임아웃 — 인증서 문제가 아니라
 *  TLS를 아예 서비스하지 않음). 실제로 접속되는 프로토콜을 그대로 적었다.
 *
 * http:// 로 등록된 것들 (inst-datainstitute, institute-fund) — 다른 이유
 *  https는 응답하지만 인증서 체인 누락(datainstitute) · 약한 DH 키(fund)로
 *  최신 브라우저/런타임이 거부할 수 있다. curl(Windows schannel)은 통과하지만
 *  Node·Chrome 최신판 기준은 더 엄격하다. 안전하게 http로 연결한다.
 *
 * 제외한 후보: care.knu.ac.kr — SSO 리다이렉트가 세션 쿠키 없이는 무한 반복돼
 *  실제 도달 가능한 페이지를 확인하지 못했다.
 */
const RAW_LINKS = [
  // ─── 핵심 시스템 ───────────────────────────────────────────
  {
    id: "knu-main",
    name: "경북대학교 홈페이지",
    nameEn: "Kyungpook National University",
    url: "https://www.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: false,
    keywords: ["메인", "공식", "대표", "본교", "knu", "홈페이지"],
    description: "대학 대표 홈페이지. 공지사항과 학사일정의 출발점.",
    featured: true,
  },
  {
    id: "portal",
    name: "통합포털",
    nameEn: "KNU Portal",
    url: "https://on.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: true,
    keywords: ["포털", "on", "통합", "로그인", "단일인증", "sso"],
    description: "학내 시스템 대부분으로 이어지는 단일 진입점.",
    featured: true,
  },
  {
    id: "sugang",
    name: "수강신청",
    nameEn: "Course Registration",
    url: "https://sugang.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: true,
    keywords: [
      "수강",
      "신청",
      "장바구니",
      "수강꾸러미",
      "시간표",
      "강의",
      "sugang",
      "예비수강",
    ],
    description: "수강신청과 수강꾸러미. 학기 초 서버가 가장 바쁜 곳.",
    healthException: "blocks-bots",
    featured: true,
  },
  {
    id: "knuin",
    name: "통합정보시스템",
    nameEn: "KNU IN",
    url: "https://knuin.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: true,
    keywords: [
      "성적",
      "학적",
      "등록금",
      "장학",
      "졸업",
      "이수",
      "knuin",
      "학사정보",
      "성적조회",
    ],
    description: "성적 조회, 학적 변동, 등록금 납부, 졸업사정.",
    healthException: "blocks-bots",
    featured: true,
  },
  {
    id: "mail",
    name: "웹메일",
    nameEn: "Webmail",
    url: "https://mail.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: true,
    keywords: ["메일", "이메일", "webmail", "mail", "학교메일"],
    description: "구성원 웹메일.",
    featured: true,
  },
  {
    id: "certpia",
    name: "인터넷 증명발급",
    nameEn: "CERTPIA",
    url: "https://certpia.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: true,
    keywords: [
      "증명서",
      "증명발급",
      "재학증명",
      "졸업증명",
      "성적증명",
      "certpia",
      "서류",
    ],
    description: "재학·졸업·성적 증명서를 온라인으로 발급.",
    healthException: "tls-mismatch",
  },
  {
    id: "knubot",
    name: "KNU BOT",
    nameEn: "KNU Chatbot",
    url: "https://knubot.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: false,
    keywords: ["챗봇", "봇", "문의", "상담", "bot", "인공지능"],
    description: "학내 안내 챗봇.",
  },
  {
    id: "knu-en",
    name: "영문 홈페이지",
    nameEn: "KNU English Site",
    url: "https://en.knu.ac.kr",
    category: "core",
    campus: "both",
    requiresLogin: false,
    keywords: ["영문", "english", "en", "외국어", "국제"],
    description: "영어권 방문자를 위한 대학 소개.",
  },

  // ─── 수업 · 학습 ───────────────────────────────────────────
  {
    id: "lms",
    name: "학습관리시스템 LMS",
    nameEn: "Learning Management System",
    url: "https://lms1.knu.ac.kr",
    category: "learning",
    campus: "both",
    requiresLogin: true,
    keywords: [
      "lms",
      "강의",
      "과제",
      "출석",
      "온라인강의",
      "이러닝",
      "퀴즈",
      "강의자료",
    ],
    description: "강의 자료, 과제 제출, 온라인 시험.",
    featured: true,
  },
  {
    id: "eclass",
    name: "공동활용 학습관리시스템",
    nameEn: "eClass",
    url: "https://eclass.knu.ac.kr",
    category: "learning",
    campus: "both",
    requiresLogin: true,
    keywords: ["eclass", "이클래스", "공동강의", "학점교류", "공유대학"],
    description: "대학 간 공동활용 강의 플랫폼.",
  },

  // ─── 도서관 · 학술 ─────────────────────────────────────────
  {
    id: "library",
    name: "중앙도서관",
    nameEn: "KUDOS Library",
    url: "https://kudos.knu.ac.kr",
    category: "library",
    campus: "daegu",
    requiresLogin: false,
    keywords: [
      "도서관",
      "kudos",
      "열람실",
      "대출",
      "자료검색",
      "논문",
      "좌석",
      "스터디룸",
    ],
    description: "자료 검색, 대출 연장, 열람실 좌석 배정.",
    featured: true,
  },
  {
    id: "ebook",
    name: "전자책 도서관",
    nameEn: "e-Book Library",
    url: "https://e-book.knu.ac.kr",
    category: "library",
    campus: "both",
    requiresLogin: true,
    keywords: ["전자책", "ebook", "이북", "전자도서"],
    description: "전자책 열람.",
  },
  {
    id: "museum",
    name: "박물관",
    nameEn: "KNU Museum",
    url: "https://museum.knu.ac.kr",
    category: "library",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["박물관", "museum", "전시", "유물"],
    description: "대학 박물관 전시와 소장품.",
  },
  {
    id: "library-mnh",
    name: "자연사박물관",
    nameEn: "Natural History Museum",
    url: "https://mnh.knu.ac.kr",
    category: "library",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["자연사", "박물관", "표본", "화석", "mnh"],
    description: "박물관(museum)과는 다른 별도 기관.",
  },
  {
    id: "library-artmuseum",
    name: "미술관",
    nameEn: "KNU Art Museum",
    url: "https://artmuseum.knu.ac.kr",
    category: "library",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["미술관", "전시", "작품", "artmuseum"],
  },

  // ─── 학생 지원 ─────────────────────────────────────────────
  {
    id: "scholarship",
    name: "장학복지제도",
    nameEn: "Scholarship & Welfare",
    url: "https://ssw.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["장학금", "장학", "복지", "학자금", "국가장학금", "ssw"],
    description: "교내외 장학금과 학생 복지 안내.",
  },
  {
    id: "dorm",
    name: "생활관 (기숙사)",
    nameEn: "Dormitory",
    url: "https://dorm.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["기숙사", "생활관", "입사", "dorm", "사생", "호실"],
    description: "생활관 입사 신청과 공지.",
  },
  {
    id: "career",
    name: "인재개발원 (취업)",
    nameEn: "Career Development Institute",
    url: "https://knujob.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["취업", "진로", "인턴", "채용", "knujob", "커리어", "자소서"],
    description: "진로 설계, 취업 상담, 채용 공고.",
  },
  {
    id: "support-hrc",
    name: "인권센터",
    nameEn: "Human Rights Center",
    url: "https://hrc.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["인권", "성희롱", "성폭력", "상담", "고충", "hrc"],
    description: "성희롱·성폭력 상담과 인권 교육.",
  },
  {
    id: "support-disability",
    name: "장애학생지원센터",
    nameEn: "Disability Student Support Center",
    url: "https://support.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["장애학생", "장애인", "편의지원", "도우미"],
  },
  {
    id: "support-ctl",
    name: "교수학습센터",
    nameEn: "Center for Teaching and Learning",
    url: "https://ctl.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["교수법", "티칭", "학습법", "비교과", "ctl"],
  },
  {
    id: "support-slc",
    name: "학습지원센터",
    nameEn: "Student Learning Center",
    url: "https://slc.knu.ac.kr",
    category: "support",
    campus: "both",
    requiresLogin: false,
    keywords: ["학습컨설팅", "튜터링", "멘토링", "slc"],
    description: "교수학습센터 산하 학습 지원 프로그램.",
  },

  // ─── 단과대학 (대구) ───────────────────────────────────────
  {
    id: "college-humanities",
    name: "인문대학",
    nameEn: "College of Humanities",
    url: "https://humanities.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["인문", "국문", "사학", "철학", "humanities", "어문"],
  },
  {
    id: "college-social",
    name: "사회과학대학",
    nameEn: "College of Social Sciences",
    url: "https://social.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["사회", "사회과학", "정치", "사회학", "심리", "social"],
  },
  {
    id: "college-cns",
    name: "자연과학대학",
    nameEn: "College of Natural Sciences",
    url: "https://cns.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["자연", "자연과학", "수학", "물리", "화학", "생물", "cns"],
  },
  {
    id: "college-cec",
    name: "경상대학",
    nameEn: "College of Economics and Commerce",
    url: "https://cec.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["경상", "경제", "경영", "무역", "회계", "cec", "상대"],
    description: "약칭이 cec다. 이름만으로는 주소를 짐작하기 어렵다.",
  },
  {
    id: "college-eng",
    name: "공과대학",
    nameEn: "College of Engineering",
    url: "https://eng.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["공대", "공과", "기계", "건축", "화공", "신소재", "eng"],
  },
  {
    id: "college-it",
    name: "IT대학",
    nameEn: "College of IT Engineering",
    url: "https://it.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["it", "컴퓨터", "전자", "전기", "소프트웨어", "컴학", "글로벌소프트웨어"],
  },
  {
    id: "college-cals",
    name: "농업생명과학대학",
    nameEn: "College of Agriculture and Life Sciences",
    url: "https://cals.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["농대", "농업", "생명과학", "임학", "원예", "cals"],
  },
  {
    id: "college-arts",
    name: "예술대학",
    nameEn: "College of Music and Visual Arts",
    url: "https://mvarts.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["예술", "예대", "음악", "미술", "디자인", "mvarts"],
    description: "주소가 mvarts다. arts.knu.ac.kr은 미술학과라 다른 곳.",
  },
  {
    id: "college-education",
    name: "사범대학",
    nameEn: "College of Education",
    url: "https://knutc.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["사범", "사대", "교육", "교직", "임용", "knutc"],
    description: "약칭이 knutc다.",
  },
  {
    id: "college-cohe",
    name: "생활과학대학",
    nameEn: "College of Human Ecology",
    url: "https://cohe.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["생활과학", "생과대", "아동", "의류", "식품영양", "cohe"],
  },
  {
    id: "college-vet",
    name: "수의과대학",
    nameEn: "College of Veterinary Medicine",
    url: "https://vet.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["수의", "수의대", "동물", "vet"],
  },
  {
    id: "college-pharmacy",
    name: "약학대학",
    nameEn: "College of Pharmacy",
    url: "https://pharmacy.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["약대", "약학", "제약", "pharmacy"],
  },
  {
    id: "college-med",
    name: "의과대학",
    nameEn: "School of Medicine",
    url: "https://med.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["의대", "의과", "의학", "med"],
  },
  {
    id: "college-dent",
    name: "치과대학",
    nameEn: "School of Dentistry",
    url: "https://dent.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["치대", "치과", "치의학", "dent"],
  },
  {
    id: "college-nurs",
    name: "간호대학",
    nameEn: "College of Nursing",
    url: "https://nurs.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["간호", "간호대", "nurs", "nursing"],
  },
  {
    id: "college-aist",
    name: "첨단기술융합대학",
    nameEn: "College of Advanced Interdisciplinary Science and Technology",
    url: "https://aist.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["첨단", "융합", "aist", "첨단기술"],
  },
  {
    id: "college-puad",
    name: "행정학부",
    nameEn: "Department of Public Administration",
    url: "https://puad.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["행정", "행정학", "puad", "공공"],
  },
  {
    id: "college-udm",
    name: "자율전공부",
    nameEn: "Undeclared Major",
    url: "https://udm.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["자율전공", "자전", "udm", "무전공", "전공선택"],
  },
  {
    id: "college-sofi",
    name: "미래인재대학",
    nameEn: "College of Self-Directed Future Talent",
    url: "https://sofi.knu.ac.kr",
    category: "college",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["미래인재", "sofi", "자기설계"],
  },

  // ─── 단과대학 (상주) ───────────────────────────────────────
  {
    id: "college-cee",
    name: "생태환경대학",
    nameEn: "College of Ecology and Environmental Science",
    url: "https://cee.knu.ac.kr",
    category: "college",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["생태", "환경", "상주", "cee"],
  },
  {
    id: "college-cst",
    name: "과학기술대학",
    nameEn: "College of Science and Technology",
    url: "https://cst.knu.ac.kr",
    category: "college",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["과학기술", "상주", "cst"],
  },

  // ─── 입학 · 대학원 · 국제 ──────────────────────────────────
  {
    id: "admission",
    name: "입학처",
    nameEn: "Office of Admissions",
    url: "https://ipsi1.knu.ac.kr",
    category: "admission",
    campus: "both",
    requiresLogin: false,
    keywords: ["입학", "입시", "수시", "정시", "원서", "ipsi", "모집요강"],
    description: "학부 입학 정보와 원서 접수.",
  },
  {
    id: "grad",
    name: "대학원",
    nameEn: "Graduate School",
    url: "https://grad.knu.ac.kr",
    category: "admission",
    campus: "both",
    requiresLogin: false,
    keywords: ["대학원", "석사", "박사", "grad", "일반대학원"],
  },
  {
    id: "grad-gse",
    name: "교육대학원",
    nameEn: "Graduate School of Education",
    url: "https://gse.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["교육대학원", "교원", "교육학", "석사"],
  },
  {
    id: "grad-gspa",
    name: "행정대학원",
    nameEn: "Graduate School of Public Administration",
    url: "https://gspa.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["행정대학원", "공공정책", "행정학"],
  },
  {
    id: "grad-gsis",
    name: "국제대학원",
    nameEn: "Graduate School of International Studies",
    url: "https://gsis.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["국제대학원", "국제학", "국제개발"],
    description: "국제처(international)와는 다른 별도의 대학원 과정.",
  },
  {
    id: "grad-health",
    name: "보건대학원",
    nameEn: "Graduate School of Public Health",
    url: "https://health.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["보건대학원", "보건학", "보건행정"],
  },
  {
    id: "grad-gpq",
    name: "식물방역대학원",
    nameEn: "Graduate School of Plant Quarantine",
    url: "https://gpq.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["식물방역", "검역", "식물검역"],
  },
  {
    id: "grad-mba",
    name: "경영대학원",
    nameEn: "Graduate School of Business",
    url: "https://mba.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["경영대학원", "mba", "경영전문"],
  },
  {
    id: "lawschool",
    name: "법학전문대학원",
    nameEn: "School of Law",
    url: "https://lawschool.knu.ac.kr",
    category: "admission",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["로스쿨", "법전원", "법학", "변호사", "lawschool"],
  },
  {
    id: "international",
    name: "국제처",
    nameEn: "Office of International Affairs",
    url: "https://international.knu.ac.kr",
    category: "admission",
    campus: "both",
    requiresLogin: false,
    keywords: ["국제", "교환학생", "유학", "어학연수", "international", "파견"],
    description: "교환학생 파견과 외국인 유학생 지원.",
  },

  // ─── 부속 · 지원기관 ───────────────────────────────────────
  {
    id: "uicc",
    name: "정보화본부",
    nameEn: "University Information & Computing Center",
    url: "https://uicc.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: false,
    keywords: ["정보화", "전산", "와이파이", "계정", "비밀번호", "uicc", "아이디"],
    description: "학내 계정, 네트워크, 시스템 공지.",
  },
  {
    id: "iac",
    name: "산학협력단",
    nameEn: "Industry-Academic Cooperation Foundation",
    url: "https://iac.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: false,
    keywords: ["산학", "연구", "과제", "협력단", "iac"],
  },
  {
    id: "oz",
    name: "IT교육센터",
    nameEn: "IT Education Center",
    url: "https://oz.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["it교육", "교육센터", "실습실", "oz"],
    healthException: "blocks-bots",
  },

  // ─── 부설연구소 · 인문사회 ─────────────────────────────────
  {
    id: "inst-rieba",
    name: "경제경영연구소",
    nameEn: "Institute of Business and Economic Research",
    url: "https://rieba.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["경제", "경영", "연구소", "rieba"],
  },
  {
    id: "inst-knuecon",
    name: "경제교육연구소",
    nameEn: "Economic Education Research Institute",
    url: "https://knuecon.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["경제교육", "경제학"],
  },
  {
    id: "inst-ripa",
    name: "공공문제연구소",
    nameEn: "Research Institute of Public Affairs",
    url: "https://ripa.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["공공문제", "정책", "행정"],
  },
  {
    id: "inst-kseri",
    name: "과학교육연구소",
    nameEn: "Korea Science Education Research Institute",
    url: "https://kseri.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["과학교육", "과학교사"],
  },
  {
    id: "inst-iewt",
    name: "동서사상연구소",
    nameEn: "Institute of East-West Thoughts",
    url: "https://iewt.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["철학", "동서사상"],
  },
  {
    id: "inst-culture",
    name: "문화산업연구소",
    nameEn: "Institute of Culture Industry",
    url: "https://culture.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["문화산업", "콘텐츠"],
  },
  {
    id: "inst-iaes",
    name: "미주유럽연구소",
    nameEn: "Institute of American and European Studies",
    url: "https://iaes.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["미주", "유럽", "지역학"],
  },
  {
    id: "inst-lawins",
    name: "법학연구원",
    nameEn: "Institute of Legal Studies",
    url: "https://lawins.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["법학", "로스쿨", "법학연구"],
  },
  {
    id: "inst-sei",
    name: "중등교육연구소",
    nameEn: "Secondary Education Research Institute",
    url: "http://sei.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["중등교육", "사범대", "교육연구"],
    description: "사범대학 부속 연구소. https 인증서가 없어 http로 연결한다.",
  },
  {
    id: "inst-riss",
    name: "사회과학연구원",
    nameEn: "Research Institute of Social Sciences",
    url: "http://riss.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["사회과학", "riss"],
    description: "https 인증서가 없어 http로 연결한다.",
  },
  {
    id: "inst-swr",
    name: "사회복지연구소",
    nameEn: "Social Welfare Research Institute",
    url: "https://swr.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["사회복지", "복지연구"],
  },
  {
    id: "inst-rieee",
    name: "에너지환경경제연구소",
    nameEn: "Research Institute for Energy and Environmental Economics",
    url: "https://rieee.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["에너지", "환경경제"],
  },
  {
    id: "inst-ynculture",
    name: "영남문화연구원",
    nameEn: "Yeungnam Culture Research Institute",
    url: "https://ynculture.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["영남", "지역문화", "전통문화"],
  },
  {
    id: "inst-iohs",
    name: "인문학술원",
    nameEn: "Institute of Humanities",
    url: "https://iohs.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["인문학", "인문학술원"],
  },
  {
    id: "inst-cba",
    name: "장수생활과학연구소",
    nameEn: "Institute of Longevity Life Science",
    url: "https://cba.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["노년", "생활과학", "장수"],
  },
  {
    id: "inst-ird",
    name: "지역개발연구소",
    nameEn: "Institute for Regional Development",
    url: "https://ird.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["지역개발", "지역연구"],
  },
  {
    id: "inst-toegye",
    name: "퇴계연구소",
    nameEn: "Toegye Studies Institute",
    url: "https://toegye.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["퇴계", "유학", "성리학"],
    healthException: "tls-mismatch",
    description: "인증서가 만료돼 브라우저 경고가 뜰 수 있다.",
  },
  {
    id: "inst-casknu",
    name: "아시아연구소",
    nameEn: "Center for Asian Studies",
    url: "https://casknu.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["아시아", "아시아연구"],
  },

  // ─── 부설연구소 · 기초과학 ─────────────────────────────────
  {
    id: "inst-oceanins",
    name: "경북해양과학연구소",
    nameEn: "Institute of Ocean Science",
    url: "https://oceanins.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["해양과학", "해양연구"],
  },
  {
    id: "inst-ipe",
    name: "계통진화유전체학연구소",
    nameEn: "Institute of Phylogenomics and Evolution",
    url: "https://ipe.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["유전체", "진화", "계통분류"],
  },
  {
    id: "inst-chep",
    name: "고에너지물리연구소",
    nameEn: "Center for High Energy Physics",
    url: "https://chep.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["물리", "고에너지물리", "입자물리"],
  },
  {
    id: "inst-ibs-knu",
    name: "기초과학연구원",
    nameEn: "KNU Institute for Basic Science",
    url: "https://ibs.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["기초과학"],
    description: "경북대 부설 연구원. 국가 기관인 IBS(기초과학연구원)와는 다른 곳이다.",
  },
  {
    id: "inst-imicrobe",
    name: "미생물연구소",
    nameEn: "Institute of Microbiology",
    url: "https://imicrobe.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["미생물", "미생물학"],
  },
  {
    id: "inst-rsri",
    name: "방사선과학연구소",
    nameEn: "Radiation Science Research Institute",
    url: "https://rsri.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["방사선", "방사선과학"],
  },
  {
    id: "inst-ndmac",
    name: "비선형동역학 수리응용센터",
    nameEn: "Nonlinear Dynamics and Mathematical Application Center",
    url: "https://ndmac.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["수학", "비선형동역학", "응용수학"],
  },
  {
    id: "inst-ori",
    name: "세포소기관연구소",
    nameEn: "Organelle Research Institute",
    url: "https://ori.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["세포생물학", "세포소기관"],
  },
  {
    id: "inst-imc",
    name: "수리융합연구소",
    nameEn: "Institute of Mathematical Convergence",
    url: "https://imc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["수리과학", "수학융합"],
  },
  {
    id: "inst-fng",
    name: "식품영양유전체연구센터",
    nameEn: "Food and Nutrition Genomics Research Center",
    url: "https://fng.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["식품영양", "유전체", "영양학"],
  },
  {
    id: "inst-abrc",
    name: "신바이오소재연구소",
    nameEn: "Advanced Bio-Resource Research Center",
    url: "https://abrc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["바이오소재", "생명자원"],
  },
  {
    id: "inst-rircm",
    name: "실및복소다양체연구소",
    nameEn: "Research Institute of Real and Complex Manifolds",
    url: "https://rircm.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["수학", "다양체", "기하학"],
  },
  {
    id: "inst-est",
    name: "환경과학기술연구소",
    nameEn: "Institute of Environmental Science and Technology",
    url: "https://est.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["환경과학", "환경기술"],
  },

  // ─── 부설연구소 · 공학 ─────────────────────────────────────
  {
    id: "inst-iedt",
    name: "공학설계연구소",
    nameEn: "Institute of Engineering Design Technology",
    url: "https://iedt.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["공학설계", "설계기술"],
  },
  {
    id: "inst-imet",
    name: "기계연구소",
    nameEn: "Institute of Mechanical Technology",
    url: "https://imet.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["기계공학", "기계연구"],
  },
  {
    id: "inst-kinpa",
    name: "나노포토닉스응용연구소",
    nameEn: "KNU Institute for Nano Photonics Application",
    url: "https://kinpa.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["나노", "포토닉스", "광학"],
  },
  {
    id: "inst-datainstitute",
    name: "데이터융복합연구원",
    nameEn: "Data Convergence Institute",
    url: "http://datainstitute.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["데이터", "빅데이터", "데이터융합"],
    description: "https 인증서 체인이 불완전해 브라우저마다 결과가 달라 http로 연결한다.",
  },
  {
    id: "inst-dataitrc",
    name: "데이터기반지능형모빌리티ICT연구센터",
    nameEn: "Data-based Intelligent Mobility ICT Research Center",
    url: "https://dataitrc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["모빌리티", "ict", "지능형교통"],
  },
  {
    id: "inst-dtrc",
    name: "디지털기술연구소",
    nameEn: "Digital Technology Research Center",
    url: "https://dtrc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["디지털기술", "디지털전환"],
  },
  {
    id: "inst-kddm",
    name: "디지털설계및생산기술연구소",
    nameEn: "Digital Design and Manufacturing Institute",
    url: "https://kddm.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["설계", "생산기술", "디지털제조"],
  },
  {
    id: "inst-mrc",
    name: "마이크로그리드연구센터",
    nameEn: "Microgrid Research Center",
    url: "https://mrc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["마이크로그리드", "전력", "스마트그리드"],
  },
  {
    id: "inst-aiwi",
    name: "물산업융복합연구소",
    nameEn: "Water Industry Convergence Research Institute",
    url: "https://aiwi.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["물산업", "수처리"],
  },
  {
    id: "inst-isft",
    name: "반도체융합기술연구원",
    nameEn: "Institute of Semiconductor Fusion Technology",
    url: "https://isft.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["반도체", "반도체융합"],
  },
  {
    id: "inst-riit",
    name: "산업기술연구소",
    nameEn: "Research Institute of Industrial Technology",
    url: "https://riit.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["산업기술", "산업연구"],
  },
  {
    id: "inst-ioid",
    name: "산업디자인연구소",
    nameEn: "Sangju Campus Industrial Design Institute",
    url: "https://ioid.knu.ac.kr",
    category: "institute",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["산업디자인", "상주캠퍼스"],
  },
  {
    id: "inst-staar",
    name: "소프트웨어재난연구센터",
    nameEn: "Software Disaster Research Center",
    url: "https://staar.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["소프트웨어", "재난안전"],
  },
  {
    id: "inst-msrc",
    name: "이동네트워크정보보호기술연구소",
    nameEn: "Mobile Network Security Research Center",
    url: "http://msrc.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["네트워크보안", "정보보호"],
    description: "https 인증서가 없어 http로 연결한다.",
  },
  {
    id: "inst-battery",
    name: "이차전지 인력양성 및 연구센터",
    nameEn: "Battery Research and Education Center",
    url: "https://battery.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["이차전지", "배터리"],
  },
  {
    id: "inst-ait",
    name: "인공지능연구원",
    nameEn: "AI Institute",
    url: "https://ait.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["인공지능", "ai"],
  },
  {
    id: "inst-eeftr",
    name: "전기에너지미래기술연구센터",
    nameEn: "Electric Energy Future Technology Research Center",
    url: "https://eeftr.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["전기에너지", "미래기술"],
  },
  {
    id: "inst-electech",
    name: "전자기술연구소",
    nameEn: "Electronic Technology Research Institute",
    url: "https://electech.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["전자기술", "전자공학연구"],
  },
  {
    id: "inst-amri",
    name: "첨단소재연구소",
    nameEn: "Advanced Materials Research Institute",
    url: "https://amri.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["첨단소재", "신소재"],
  },
  {
    id: "inst-connected",
    name: "초연결융합기술연구소",
    nameEn: "Hyper-connected Convergence Technology Institute",
    url: "https://connected.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["초연결", "융합기술"],
  },
  {
    id: "inst-a3",
    name: "A3 건축연구소",
    nameEn: "A3 Architecture Research Institute",
    url: "https://a3.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["건축", "건축연구"],
  },
  {
    id: "inst-idec",
    name: "IDEC지역센터",
    nameEn: "IDEC Regional Center",
    url: "https://idec.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["반도체설계교육", "idec"],
  },
  {
    id: "aerodrone",
    name: "항공드론 혁신융합대학사업단",
    url: "https://aerodrone.knu.ac.kr/",
    category: "institute",
    campus: "both",  // 캠퍼스를 확인해 필요하면 daegu/sangju로 바꾸세요
    requiresLogin: false,
    keywords: [],  // TODO: 검색 별칭 채우기
  },

  // ─── 부설연구소 · 농업생명과학 ─────────────────────────────
  {
    id: "inst-iard",
    name: "국제개발연구원",
    nameEn: "Institute of International Agricultural Development",
    url: "https://iard.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["국제농업개발", "농업협력"],
  },
  {
    id: "inst-kaqs",
    name: "농산물품질·안전성평가연구소",
    nameEn: "Agricultural Products Quality and Safety Institute",
    url: "https://kaqs.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["농산물", "품질평가", "안전성"],
  },
  {
    id: "inst-iast",
    name: "농업과학기술연구소",
    nameEn: "Institute of Agricultural Science and Technology",
    url: "https://iast.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["농업과학", "농업기술"],
  },
  {
    id: "inst-riias",
    name: "미래동물자원연구원",
    nameEn: "Institute of Animal Science Research",
    url: "https://riias.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["동물자원", "축산"],
  },
  {
    id: "inst-umrc",
    name: "밭농업기계개발연구센터",
    nameEn: "Upland Farming Mechanization Research Center",
    url: "https://umrc.knu.ac.kr",
    category: "institute",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["농업기계", "밭농업", "상주캠퍼스"],
  },
  {
    id: "inst-ipm",
    name: "식물의학연구소",
    nameEn: "Institute of Plant Medicine",
    url: "https://ipm.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["식물의학", "병해충"],
  },
  {
    id: "inst-fbri",
    name: "식품생물산업연구소",
    nameEn: "Food and Bio-industry Research Institute",
    url: "https://fbri.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["식품산업", "바이오산업"],
  },

  // ─── 부설연구소 · 의과학 ───────────────────────────────────
  {
    id: "inst-nlab",
    name: "간호혁신연구소",
    nameEn: "Nursing Innovation Research Institute",
    url: "https://nlab.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["간호", "간호혁신"],
  },
  {
    id: "inst-brain",
    name: "뇌과학연구소",
    nameEn: "Brain Science and Engineering Institute",
    url: "https://brain.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["뇌과학", "신경과학"],
  },
  {
    id: "inst-nrs",
    name: "뇌수술로봇시스템연구소",
    nameEn: "Neurosurgical Robot System Research Institute",
    url: "http://nrs.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["뇌수술", "의료로봇"],
    description: "https 인증서가 없어 http로 연결한다.",
  },
  {
    id: "inst-cmri",
    name: "세포·기질연구소",
    nameEn: "Cell and Matrix Research Institute",
    url: "https://cmri.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["세포생물학", "기질연구"],
    healthException: "tls-mismatch",
    description: "인증서가 만료돼 브라우저 경고가 뜰 수 있다.",
  },
  {
    id: "inst-rips",
    name: "약학연구소",
    nameEn: "Research Institute of Pharmaceutical Sciences",
    url: "https://rips.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["약학", "약학연구"],
  },
  {
    id: "inst-ibme",
    name: "의공학연구소",
    nameEn: "Institute of Biomedical Engineering Research",
    url: "https://ibme.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["의공학", "생체공학"],
  },
  {
    id: "inst-a3di",
    name: "첨단치과의료기기개발연구소",
    nameEn: "Advanced Dental Medical Device R&D Institute",
    url: "http://a3di.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["치과의료기기", "치의학"],
    description: "https 인증서가 없어 http로 연결한다.",
  },
  {
    id: "inst-voice2020",
    name: "혈관장기상호작용제어연구센터",
    nameEn: "Vascular-Organ Interaction Control Research Center",
    url: "https://voice2020.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["혈관", "순환기"],
  },

  // ─── 행정·부속 지원기관 ────────────────────────────────────
  {
    id: "institute-alumni",
    name: "총동창회",
    nameEn: "KNU Alumni Association",
    url: "https://alumni.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: false,
    keywords: ["동창회", "총동문", "동문회"],
  },
  {
    id: "institute-fund",
    name: "발전기금",
    nameEn: "KNU Development Fund",
    url: "http://fund.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: false,
    keywords: ["발전기금", "기부", "후원"],
    description: "https가 오래된 TLS 설정(약한 DH 키)이라 최신 브라우저가 거부할 수 있어 http로 연결한다.",
  },
  {
    id: "institute-ir",
    name: "IR센터",
    nameEn: "Institutional Research Center",
    url: "https://ir.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: true,
    keywords: ["대학통계", "ir", "기관연구"],
  },
  {
    id: "institute-safe",
    name: "연구실안전관리시스템",
    nameEn: "Lab Safety Management System",
    url: "https://safe.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: true,
    keywords: ["실험실안전", "연구실안전", "안전교육"],
  },
  {
    id: "institute-kpcl",
    name: "공동실험실습관",
    nameEn: "Joint Research Equipment Center",
    url: "https://kpcl.knu.ac.kr",
    category: "institute",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["공동장비", "실험기기", "장비예약"],
  },
  {
    id: "institute-iams",
    name: "통합연구행정지원시스템",
    nameEn: "Integrated Research Administration Support System",
    url: "https://iams.knu.ac.kr",
    category: "institute",
    campus: "both",
    requiresLogin: true,
    keywords: ["연구비", "연구행정", "산학협력"],
  },

  // ─── 부속병원 ──────────────────────────────────────────────
  {
    id: "hospital-knuh",
    name: "경북대학교병원",
    nameEn: "Kyungpook National University Hospital",
    url: "https://www.knuh.kr",
    category: "hospital",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["병원", "본원", "진료", "예약", "knuh", "삼덕동"],
    description: "대구 중구 본원. 도메인이 knuh.kr로 다르다.",
  },
  {
    id: "hospital-knuch",
    name: "칠곡경북대학교병원",
    nameEn: "Kyungpook National University Chilgok Hospital",
    url: "https://www.knuch.kr",
    category: "hospital",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["칠곡", "병원", "학정동", "knuch"],
  },
  {
    id: "hospital-knudh",
    name: "경북대학교치과병원",
    nameEn: "KNU Dental Hospital",
    url: "https://knudh.kr",
    category: "hospital",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["치과병원", "치과", "knudh"],
  },

  // ─── 언론 · 소셜 ───────────────────────────────────────────
  {
    id: "press",
    name: "신문방송사",
    nameEn: "KNU Press Center",
    url: "https://www.knupresscenter.com",
    category: "media",
    campus: "both",
    requiresLogin: false,
    keywords: ["신문", "방송", "경북대신문", "언론", "학보", "kbs"],
    description: "경북대신문, KNU Times, 교내방송.",
  },
  {
    id: "instagram-official",
    name: "공식 인스타그램",
    nameEn: "Official Instagram",
    url: "https://www.instagram.com/knuofficial/",
    category: "media",
    campus: "both",
    requiresLogin: false,
    keywords: ["인스타", "인스타그램", "sns", "instagram", "공식"],
  },
  {
    id: "instagram-council",
    name: "총학생회 인스타그램",
    nameEn: "Student Council Instagram",
    url: "https://www.instagram.com/knu_ch/",
    category: "media",
    campus: "both",
    requiresLogin: false,
    keywords: ["총학", "총학생회", "학생회", "인스타", "instagram"],
    description: "총학생회는 별도 홈페이지 없이 SNS로 소식을 알린다.",
  },

  /* ── 학과 · 전공 홈페이지 ──
     college 사이트에서 열거해 curl로 생존 확인한 학부·학과. 주소가 학과
     이름과 규칙적으로 대응하지 않아(soft=소프트웨어X, se=소프트웨어) 검색
     가치가 크다. BK21 사업단·개인 연구실·영문 미러·동창회는 제외했다. */
  {
    id: "dept-biz",
    name: "경상대학 경영학부",
    url: "https://biz.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["biz", "학과"],
  },
  {
    id: "dept-econ",
    name: "경상대학 경제통상학부",
    url: "https://econ.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["econ", "학과"],
  },
  {
    id: "dept-polymer",
    name: "고분자공학과",
    url: "https://polymer.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["polymer", "학과"],
  },
  {
    id: "dept-ento",
    name: "곤충생명과학과",
    url: "https://ento.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["ento", "학과"],
  },
  {
    id: "dept-arch",
    name: "공과대학 건축학부",
    url: "https://arch.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["arch", "학과"],
  },
  {
    id: "dept-me",
    name: "공과대학 기계공학부",
    url: "https://me.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["me", "학과"],
  },
  {
    id: "dept-textile-eng",
    name: "공과대학 섬유시스템공학과",
    url: "https://textile-eng.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["textile-eng", "학과"],
  },
  {
    id: "dept-mse",
    name: "공과대학 신소재공학과",
    url: "https://mse.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["mse", "학과"],
  },
  {
    id: "dept-appchem",
    name: "공과대학 응용화학과",
    url: "https://appchem.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["appchem", "학과"],
  },
  {
    id: "dept-civil",
    name: "공과대학 토목공학과",
    url: "https://civil.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["civil", "학과"],
  },
  {
    id: "dept-env",
    name: "공과대학 환경공학과",
    url: "https://env.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["env", "학과"],
  },
  {
    id: "dept-disaster",
    name: "과학기술대학 건설방재공학과",
    url: "https://disaster.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["disaster", "학과"],
  },
  {
    id: "dept-knu-amse",
    name: "과학기술대학 나노신소재공학과",
    url: "https://knu-amse.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["knu-amse", "학과"],
  },
  {
    id: "dept-se",
    name: "과학기술대학 소프트웨어학과",
    url: "https://se.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["se", "학과"],
  },
  {
    id: "dept-smartplant",
    name: "과학기술대학 스마트플랜트공학과",
    url: "https://smartplant.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["smartplant", "학과"],
  },
  {
    id: "dept-ffsi",
    name: "과학기술대학 식품외식산업학과",
    url: "https://ffsi.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["ffsi", "학과"],
  },
  {
    id: "dept-cfse",
    name: "과학기술대학 융복합시스템공학부",
    url: "https://cfse.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["cfse", "학과"],
  },
  {
    id: "dept-auto",
    name: "과학기술대학 자동차공학과",
    url: "https://auto.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["auto", "학과"],
  },
  {
    id: "dept-pme",
    name: "과학기술대학 정밀기계공학과",
    url: "https://pme.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["pme", "학과"],
  },
  {
    id: "dept-dehy",
    name: "과학기술대학 치위생학과",
    url: "https://dehy.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["dehy", "학과"],
  },
  {
    id: "dept-style",
    name: "과학기술대학 패션디자인전공",
    url: "https://style.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["style", "학과"],
  },
  {
    id: "dept-seoksa",
    name: "과학기술대학원",
    url: "https://seoksa.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["seoksa", "학과"],
  },
  {
    id: "dept-tour",
    name: "관광학과",
    url: "https://tour.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["tour", "학과"],
  },
  {
    id: "dept-korean",
    name: "국어국문학과",
    url: "https://korean.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["korean", "학과"],
  },
  {
    id: "dept-metal",
    name: "금속재료공학과",
    url: "https://metal.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["metal", "학과"],
  },
  {
    id: "dept-aifm",
    name: "농업생명과학대학 농산업학과",
    url: "https://aifm.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["aifm", "학과"],
  },
  {
    id: "dept-acen",
    name: "농업생명과학대학 농업토목공학과",
    url: "https://acen.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["acen", "학과"],
  },
  {
    id: "dept-biofiber",
    name: "농업생명과학대학 바이오섬유소재학과",
    url: "https://biofiber.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["biofiber", "학과"],
  },
  {
    id: "dept-bime",
    name: "농업생명과학대학 스마트생물산업기계공학과",
    url: "https://bime.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["bime", "학과"],
  },
  {
    id: "dept-pbs",
    name: "농업생명과학대학 식물생명과학전공",
    url: "https://pbs.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["pbs", "학과"],
  },
  {
    id: "dept-plantmed",
    name: "농업생명과학대학 식물의학과",
    url: "https://plantmed.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["plantmed", "학과"],
  },
  {
    id: "dept-foodbio",
    name: "농업생명과학대학 식품공학부",
    url: "https://foodbio.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["foodbio", "학과"],
  },
  {
    id: "dept-horti",
    name: "농업생명과학대학 원예과학과",
    url: "https://horti.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["horti", "학과"],
  },
  {
    id: "dept-abs",
    name: "농업생명과학대학 응용생명과학부",
    url: "https://abs.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["abs", "학과"],
  },
  {
    id: "dept-agbl",
    name: "농업생명과학대학 응용생물학전공",
    url: "https://agbl.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["agbl", "학과"],
  },
  {
    id: "dept-wood",
    name: "농업생명과학대학 임산공학전공",
    url: "https://wood.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["wood", "학과"],
  },
  {
    id: "dept-forestry",
    name: "농업생명과학대학 임학전공",
    url: "https://forestry.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["forestry", "학과"],
  },
  {
    id: "dept-land",
    name: "농업생명과학대학 조경학 전공",
    url: "https://land.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["land", "학과"],
  },
  {
    id: "dept-kac",
    name: "농업생명과학대학 환경생명화학전공",
    url: "https://kac.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["kac", "학과"],
  },
  {
    id: "dept-ai",
    name: "대학원 인공지능학과",
    url: "https://ai.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["ai", "학과"],
  },
  {
    id: "dept-mediacomm",
    name: "미디어커뮤니케이션학과",
    url: "https://mediacomm.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["mediacomm", "학과"],
  },
  {
    id: "dept-edu",
    name: "사범대학 교육학과",
    url: "https://edu.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["edu", "학과"],
  },
  {
    id: "dept-fredu",
    name: "사범대학 불어교육전공",
    url: "https://fredu.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["fredu", "학과"],
  },
  {
    id: "dept-geredu",
    name: "사범대학 유럽어교육학부독어교육전공",
    url: "https://geredu.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["geredu", "학과"],
  },
  {
    id: "dept-lis",
    name: "사회과학대학 문헌정보학과",
    url: "https://lis.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["lis", "학과"],
  },
  {
    id: "dept-socio",
    name: "사회과학대학 사회학과",
    url: "https://socio.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["socio", "학과"],
  },
  {
    id: "dept-politics",
    name: "사회과학대학 정치외교학과",
    url: "https://politics.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["politics", "학과"],
  },
  {
    id: "dept-geog",
    name: "사회과학대학 지리학과",
    url: "https://geog.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["geog", "학과"],
  },
  {
    id: "dept-knusw",
    name: "사회복지학부",
    url: "https://knusw.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["knusw", "학과"],
  },
  {
    id: "dept-biotech",
    name: "생명공학부",
    url: "https://biotech.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["biotech", "학과"],
  },
  {
    id: "dept-anibiotech",
    name: "생태환경대학 동물생명공학과",
    url: "https://anibiotech.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["anibiotech", "학과"],
  },
  {
    id: "dept-axt",
    name: "생태환경대학 말/특수동물학과",
    url: "https://axt.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["axt", "학과"],
  },
  {
    id: "dept-forest",
    name: "생태환경대학 산림생태보호학과",
    url: "https://forest.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["forest", "학과"],
  },
  {
    id: "dept-dols",
    name: "생태환경대학 체육학부",
    url: "https://dols.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["dols", "학과"],
  },
  {
    id: "dept-ani",
    name: "생태환경대학 축산학과",
    url: "https://ani.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["ani", "학과"],
  },
  {
    id: "dept-fsnu",
    name: "생활과학대학 식품영양학과",
    url: "https://fsnu.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["fsnu", "학과"],
  },
  {
    id: "dept-child",
    name: "생활과학대학 아동학부",
    url: "https://child.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["child", "학과"],
  },
  {
    id: "dept-fashion",
    name: "생활과학대학 의류학과",
    url: "https://fashion.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["fashion", "학과"],
  },
  {
    id: "dept-scplant",
    name: "식물자원학과",
    url: "https://scplant.knu.ac.kr",
    category: "department",
    campus: "sangju",
    requiresLogin: false,
    keywords: ["scplant", "학과"],
  },
  {
    id: "dept-psy",
    name: "심리학과",
    url: "https://psy.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["psy", "학과"],
  },
  {
    id: "dept-ece",
    name: "에너지화학공학과",
    url: "https://ece.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["ece", "학과"],
  },
  {
    id: "dept-kmusic",
    name: "예술대학 국악학과",
    url: "https://kmusic.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["kmusic", "학과"],
  },
  {
    id: "dept-vcd",
    name: "예술대학 디자인학과",
    url: "https://vcd.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["vcd", "학과"],
  },
  {
    id: "dept-arts",
    name: "예술대학 미술학과",
    url: "https://arts.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["arts", "학과"],
  },
  {
    id: "dept-music",
    name: "예술대학 음악학과",
    url: "https://music.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["music", "학과"],
  },
  {
    id: "dept-aerospace",
    name: "우주공학부",
    url: "https://aerospace.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["aerospace", "학과"],
  },
  {
    id: "dept-lbis",
    name: "위치정보시스템학과",
    url: "https://lbis.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["lbis", "학과"],
  },
  {
    id: "dept-aran",
    name: "인문대학 고고인류학과",
    url: "https://aran.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["aran", "학과"],
  },
  {
    id: "dept-german",
    name: "인문대학 독어독문학과",
    url: "https://german.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["german", "학과"],
  },
  {
    id: "dept-france",
    name: "인문대학 불어불문학과",
    url: "https://france.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["france", "학과"],
  },
  {
    id: "dept-khistory",
    name: "인문대학 사학과",
    url: "https://khistory.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["khistory", "학과"],
  },
  {
    id: "dept-english",
    name: "인문대학 영어영문학과",
    url: "https://english.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["english", "학과"],
  },
  {
    id: "dept-japan",
    name: "인문대학 일어일문학과",
    url: "https://japan.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["japan", "학과"],
  },
  {
    id: "dept-hudm",
    name: "인문대학 자율학부",
    url: "https://hudm.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["hudm", "학과"],
  },
  {
    id: "dept-philosophy",
    name: "인문대학 철학과",
    url: "https://philosophy.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["philosophy", "학과"],
  },
  {
    id: "dept-hanmun",
    name: "인문대학 한문학과",
    url: "https://hanmun.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["hanmun", "학과"],
  },
  {
    id: "dept-physics",
    name: "자연과학대학 물리학과",
    url: "https://physics.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["physics", "학과"],
  },
  {
    id: "dept-bio",
    name: "자연과학대학 생물학과",
    url: "https://bio.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["bio", "학과"],
  },
  {
    id: "dept-math",
    name: "자연과학대학 수학과",
    url: "https://math.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["math", "학과"],
  },
  {
    id: "dept-geology",
    name: "자연과학대학 지질학전공",
    url: "https://geology.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["geology", "학과"],
  },
  {
    id: "dept-stat",
    name: "자연과학대학 통계학과",
    url: "https://stat.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["stat", "학과"],
  },
  {
    id: "dept-ocean",
    name: "자연과학대학 해양학전공",
    url: "https://ocean.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["ocean", "학과"],
  },
  {
    id: "dept-chem",
    name: "자연과학대학 화학과",
    url: "https://chem.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["chem", "학과"],
  },
  {
    id: "dept-chinese",
    name: "중어중문학과",
    url: "https://chinese.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["chinese", "학과"],
  },
  {
    id: "dept-computer",
    name: "컴퓨터학부",
    url: "https://computer.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["computer", "학과"],
  },
  {
    id: "dept-cheme",
    name: "화학공학과",
    url: "https://cheme.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["cheme", "학과"],
  },
  {
    id: "dept-ue",
    name: "환경안전공학과",
    url: "https://ue.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["ue", "학과"],
  },
  {
    id: "dept-electric",
    name: "IT대학 전기공학과",
    url: "https://electric.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["electric", "학과"],
  },
  {
    id: "dept-see",
    name: "IT대학 전자공학부",
    url: "https://see.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["see", "학과"],
  },
  {
    id: "dept-smobile",
    name: "IT대학 전자공학부 모바일공학전공",
    url: "https://smobile.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["smobile", "학과"],
  },
  {
    id: "dept-seeai",
    name: "IT대학 전자공학부 인공지능전공",
    url: "https://seeai.knu.ac.kr",
    category: "department",
    campus: "daegu",
    requiresLogin: false,
    keywords: ["seeai", "학과"],
  },
] as const satisfies readonly KnuLink[];

/**
 * `as const satisfies` 는 위 리터럴을 컴파일 타임에 검증하지만 타입을 튜플로 좁힌다.
 * 소비하는 쪽에는 넓은 타입을 준다 — 개별 링크의 리터럴 타입은 아무도 필요로 하지 않는다.
 */
export const LINKS: readonly KnuLink[] = RAW_LINKS;

export const FEATURED_LINKS: readonly KnuLink[] = LINKS.filter((l) => l.featured);

/** id → 링크. 통계 응답을 링크로 되돌릴 때 쓴다. */
export const LINK_BY_ID: ReadonlyMap<string, KnuLink> = new Map(
  LINKS.map((l) => [l.id, l]),
);
